config/routes.rb
Rails.application.routes.draw do
  root 'tweets#index'
  resources :users
  resources :tweets
  get '/sign_up' => 'users#new'
  post '/users' => 'users#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/list.rb
class List < ApplicationRecord
  has_many :list_members
  has_many :members, through: :list_members, source: :user

  has_many :list_subscribers
  has_many :subscribers, through: :list_subscribers, source: :user

  belongs_to :user
end

app/models/list_member.rb
class ListMember < ApplicationRecord
  belongs_to :list
  belongs_to :user
end

app/models/list_subscriber.rb
class ListSubscriber < ApplicationRecord
  belongs_to :list
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/retweet.rb
class Retweet < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tagged_tweets
  has_many :tweets, through: :tagged_tweets
end

app/models/tagged_tweet.rb
class TaggedTweet < ApplicationRecord
  belongs_to :tag
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  default_scope { includes(:user) }
  belongs_to :user
  has_many :tagged_tweets
  has_many :tags, through: :tagged_tweets
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :tweets, dependent: :destroy
  accepts_nested_attributes_for :tweets

  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed

  has_many :other_tweets,         class_name:  "Retweet",
                                  foreign_key: "retweeter_id",
                                  dependent:   :destroy
  has_many :retweets, through: :other_tweets, source: :tweet

  has_many :favorites, dependent: :destroy
  has_many :favorite_tweets, through: :favorites, source: :tweet

  has_many :lists, foreign_key: "author_id", dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to @tweet.user
    else
      render 'new'
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:tweet, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = current_user
    @tweet = Tweet.new
  end

  def edit
  end

  private

    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

    def current_user
      User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_css_overrides.html.erb
<% if Rails.env.test? %>
  <style type="text/css">
    * {
      transition-property: none !important;
    }
  </style>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <%= render "flashes" -%>
  <div class="bigbox">
    <%= render "partials/navbar" %>
    <%= yield %>
  </div>
  <%= render "javascript" %>
  <%= render "css_overrides" %>
</body>
</html>

app/views/partials/_navbar.html.erb
<header class="navigation" role="banner">
  <div class="navigation-wrapper">
    <%= image_tag "https://g.twimg.com/about/feature-corporate/image/twitterbird_RGB.png", class: "logo" %>
    <a href="javascript:void(0)" class="navigation-menu-button" id="js-mobile-menu">MENU</a>
    <nav role="navigation">
      <ul id="js-navigation-menu" class="navigation-menu show">
        <li class="nav-link"><%= link_to 'Home', '/' %></li>
        <li class="nav-link"><%= link_to 'Connect', '#' %></li>
        <li class="nav-link"><%= link_to 'Discover', '#' %></li>
      </ul>
    </nav>
    <nav role="navigation-right" style="float: right;">
      <ul id="js-navigation-menu" class="navigation-menu show">
        <li id="js-navigation-more" class="nav-link more"><%= link_to 'Account', '#' %>
        <ul class="submenu">
          <li><%= link_to 'Sign in', '#' %></li>
          <li><%= link_to 'Sign out', '#' %></li>
          <li><%= link_to 'Sign up', new_user_path %></li>
        </ul>
        <li class="nav-link"><%= link_to 'Tweet', '#' %></li>
        <li>
      </ul>
    </nav>
    <div class="navigation-tools">
      <div class="search-bar">
        <form role="search">
          <input type="search" placeholder="Search User/Tweet" />
          <button type="submit">
            <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/search-icon.png" alt="Search Icon">
          </button>
        </form>
      </div>
    </div>
  </div>
</header>

app/views/tweets/_create_tweet.html.erb
<h1>Create Tweet:</h1>
<%= simple_form_for @tweet do |f| %>
  <%= f.hidden_field :user_id, value: params[:id] %>
  <%= f.input :tweet %>
  <%= f.button :submit %>
<% end %>

app/views/tweets/_tweet.html.erb
<div id="row">
  <div class="tweet">
    <%= link_to(tweet.user.username, user_path(tweet.user)) %>: <%= tweet.tweet %>
  </div>
</div>

app/views/tweets/index.html.erb
<div class="tweet-feed">
  <%= render @tweets %>
</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="col-3">
  <%= simple_form_for @user do |f| %>
    <%= f.input :username, label: 'Username', error: 'Input a Username' %>
    <%= f.input :email, placeholder: 'user@twitterclone.com' %>
    <%= f.input :password, error: 'No special characters' %>
    <%= f.input :password_confirmation, error: 'Must match password' %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/users/show.html.erb
<%= @user.username %>

<%= render @user.tweets %>


<%= render 'tweets/create_tweet' %>